name: Build web artifacts
on: [push]

jobs:
  build:
    name: Build web artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Build directories
        shell: bash
        run: mkdir repository; mkdir pharo-ide
        
      - name: Checkout exercism/pharo
        uses: actions/checkout@v2
        with:
          path: repository
          ref: '' # This should default to the branch and reference that triggered the workflow.

      - name: Fetch configlet tool
        shell: bash
        run: "./repository/bin/fetch-configlet"
        timeout-minutes: 10
        
      - name: Download Pharo image and virtual machine
        shell: bash
        run: cd pharo-ide; curl -L get.pharo.org/80+vm | bash
        timeout-minutes: 15

      - name: Hello world
        if: ${{ success() }}
        run: "./pharo-ide/pharo pharo-ide/Pharo.image perform Transcript show: 'Hello world!'"
